#include "csb.hpp"

#include <algorithm>
#include <cstddef>
#include <filesystem>
#include <format>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>

void csb::configure()
{
  csb::target_name = "CSEngine";
  csb::target_artifact = EXECUTABLE;
  csb::target_linkage = STATIC;
  csb::target_subsystem = CONSOLE;
  csb::target_configuration = RELEASE;
  csb::cxx_standard = CXX20;
  csb::warning_level = W4;
  csb::include_files = csb::files_from({"program/include"}, {}, {"program/include/resource.hpp"});
  csb::source_files = csb::files_from({"program/source"}, {}, {"program/source/resource.cpp"});
  if (csb::host_platform == WINDOWS)
    csb::libraries = {"kernel32", "user32",   "shell32",  "gdi32",       "imm32", "comdlg32",
                      "ole32",    "oleaut32", "advapi32", "dinput8",     "winmm", "winspool",
                      "setupapi", "uuid",     "version",  "SDL3-static", "glm"};
  else if (csb::host_platform == LINUX)
    csb::libraries = {"c", "m", "pthread", "dl", "SDL3", "glm"};
}

int csb::clean()
{
  csb::clean_build_directory();
  csb::remove_files({"program/include/resource.hpp", "program/source/resource.cpp"});
  return csb::build();
}

int csb::build()
{
  if (!csb::is_subproject)
    csb::clang_format("21.1.1", csb::files_from({"program/shader"}),
                      {"program/include/resource.hpp", "program/source/resource.cpp"});

  csb::archive_install(
    {{csb::host_platform == WINDOWS
        ? "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2505.1/dxc_2025_07_14.zip"
        : "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2505.1/"
          "linux_dxc_2025_07_14.x86_64.tar.gz",
      "build/dxc",
      {csb::host_platform == WINDOWS ? "bin/" + csb::host_architecture : "bin",
       csb::host_platform == WINDOWS ? "lib/" + csb::host_architecture : "lib"}}});
  if (csb::host_platform == LINUX)
  {
    csb::multi_task_run("chmod +x ()", csb::files_from({"build/dxc"}, {""}), {"build/dxc/executable.(filename)"});
    csb::prepend_environment_variable("LD_LIBRARY_PATH", "build/dxc");
  }
  csb::multi_task_run(
    [](const std::filesystem::path &file, const auto &, const auto &) -> std::string
    {
      return std::format("{} -spirv -T {}_6_0 -E main () -Fo []",
                         csb::host_platform == WINDOWS ? "build\\dxc\\dxc.exe" : "./build/dxc/dxc",
                         file.extension() == ".vert" ? "vs" : "ps");
    },
    csb::files_from({"program/shader"}), {"build/shader/(filename).spv"});

  using group_name = std::string;
  using group_range = std::pair<unsigned int, unsigned int>;
  using frame_group = std::pair<group_name, group_range>;
  using frame_groups = std::vector<frame_group>;
  using frame_dimensions = std::pair<unsigned int, unsigned int>;
  using frame_data = std::pair<frame_dimensions, frame_groups>;
  std::unordered_map<std::filesystem::path, frame_data> frame_map{};
  for (const auto &object : csb::read_file<nlohmann::json>("program/texture/frames.json"))
  {
    const auto &file{object["file"].get<std::filesystem::path>()};
    const auto &dimensions{object["frame_dimensions"].get<frame_dimensions>()};
    frame_groups groups{};
    for (const auto &group : object["frame_groups"])
      groups.emplace_back(group["name"].get<group_name>(), group["range"].get<group_range>());
    frame_map.emplace(file, frame_data{dimensions, groups});
  }

  using binary_data = std::vector<std::byte>;
  using width = unsigned int;
  using height = unsigned int;
  using channels = unsigned int;
  using image_data = std::tuple<width, height, channels>;
  using texture_data = std::tuple<image_data, frame_data>;
  using resource = std::tuple<binary_data, texture_data>;
  csb::embed<resource>(
    {"// This file is automatically generated, do not edit manually.\n\n"
     "#pragma once\n\n"
     "#include <algorithm>\n"
     "#include <cstddef>\n"
     "#include <span>\n"
     "#include <string_view>\n"
     "#include <utility>\n\n"
     "#include \"exception.hpp\"\n\n"
     "namespace cse::resource\n"
     "{\n"
     "  struct compiled_shader\n"
     "  {\n"
     "    const std::span<const unsigned char> source{};\n"
     "    const std::size_t length{};\n"
     "  };\n"
     "  struct compiled_texture\n"
     "  {\n"
     "    struct image_data\n"
     "    {\n"
     "      const unsigned int width{};\n"
     "      const unsigned int height{};\n"
     "      const unsigned int channels{};\n"
     "    };\n"
     "    struct frame_data\n"
     "    {\n"
     "      struct group\n"
     "      {\n"
     "        struct frame\n"
     "        {\n"
     "          struct rect\n"
     "          {\n"
     "            const float top{};\n"
     "            const float left{};\n"
     "            const float bottom{};\n"
     "            const float right{};\n"
     "          };\n"
     "          const rect coords{};\n"
     "        };\n"
     "        const unsigned int start_frame{};\n"
     "        const unsigned int end_frame{};\n"
     "        const std::span<const frame> frames{};\n"
     "      };\n"
     "      const group &find_group(std::string_view name) const\n"
     "      {\n"
     "        auto it{std::lower_bound(groups.begin(), groups.end(), name,\n"
     "                                 [](const auto &pair, std::string_view key) { return pair.first < key; })};\n"
     "        if (it == groups.end() || it->first != name)\n"
     "          throw utility::exception(\"Could not find '{}' frame group for texture\", name);\n"
     "        return it->second;\n"
     "      };\n"
     "      const unsigned int width{};\n"
     "      const unsigned int height{};\n"
     "      const std::span<const std::pair<std::string_view, group>> groups{};\n"
     "    };\n"
     "    const std::span<const unsigned char> image{};\n"
     "    const image_data image_data{};\n"
     "    const frame_data frame_data{};\n"
     "  };\n\n",
     "// This file is automatically generated, do not edit manually.\n\n"
     "#include \"resource.hpp\"\n\n"
     "#include <array>\n"
     "#include <string_view>\n"
     "#include <utility>\n\n"
     "namespace cse::resource\n"
     "{\n"},
    {nullptr,
     [](const std::filesystem::path &file, const std::string &name, const resource &) -> std::string
     {
       if (file.extension() == ".spv")
         return std::format("  static constexpr std::array<const unsigned char, (1)> {}_data{{\n    (0)}};\n\n", name);
       else
         return std::format("  static constexpr std::array<const unsigned char, (1)> {}_image{{\n    (0)}};\n(2)\n\n",
                            name);
     },
     [](const std::filesystem::path &file) -> std::string
     {
       if (file.extension() == ".spv")
       {
         if (file.stem().extension() == ".vert")
           return file.stem().stem().string() + "_vertex";
         else
           return file.stem().stem().string() + "_fragment";
       }
       else
         return file.stem().string() + "_texture";
     },
     [&frame_map](const std::filesystem::path &file) -> resource
     {
       if (file.extension() == ".spv")
         return {csb::read_file<binary_data>(file), {}};
       else
       {
         stbi_set_flip_vertically_on_load(true);
         auto image{csb::read_file<csb::image>(file)};
         const auto &[frame_dimensions, frame_groups]{frame_map.at(file.filename())};
         return {image.data, {{image.width, image.height, image.channels}, {frame_dimensions, frame_groups}}};
       }
     },
     [](const std::string &name, const resource &data) -> std::vector<std::string>
     {
       std::vector<std::string> results{};
       const auto &[binary_data, texture_data]{data};

       std::string binary_data_result{};
       for (std::size_t index{}; index < binary_data.size(); ++index)
       {
         binary_data_result += csb::byte_to_hex(binary_data[index]);
         if (index < binary_data.size() - 1)
         {
           binary_data_result += ",";
           if ((index + 1) % 16 == 0)
             binary_data_result += "\n    ";
           else
             binary_data_result += " ";
         }
       }
       results.push_back(binary_data_result);
       results.push_back(std::to_string(binary_data.size()));

       const auto &[image_data, frame_data]{texture_data};
       const auto &[width, height, channels]{image_data};
       const auto &[frame_dimensions, frame_groups]{frame_data};
       const auto &[frame_width, frame_height]{frame_dimensions};
       if (width == 0 || height == 0 || channels == 0 || frame_width == 0 || frame_height == 0 || frame_groups.empty())
         return results;
       const unsigned int frames_per_row{width / frame_width};
       const unsigned int frames_per_column{height / frame_height};
       std::string groups_result{};
       for (const auto &frame_group : frame_groups)
       {
         const auto &[group_name, frame_range]{frame_group};
         const auto &[start_frame, end_frame]{frame_range};
         groups_result += std::format("  static constexpr std::array<const compiled_texture::frame_data::group::frame, "
                                      "{}> {}_{}_frames{{\n    {{",
                                      end_frame - start_frame + 1, name, group_name);
         for (unsigned int frame_index{start_frame - 1}; frame_index < end_frame; ++frame_index)
         {
           const unsigned int frame_x{frame_index % frames_per_row};
           const unsigned int frame_y{(frames_per_column - 1) - (frame_index / frames_per_row)};
           const float top{static_cast<float>((frame_y + 1) * frame_height) / static_cast<float>(height)};
           const float left{static_cast<float>(frame_x * frame_width) / static_cast<float>(width)};
           const float bottom{static_cast<float>(frame_y * frame_height) / static_cast<float>(height)};
           const float right{static_cast<float>((frame_x + 1) * frame_width) / static_cast<float>(width)};
           groups_result += std::format("{{{:#g}f, {:#g}f, {:#g}f, {:#g}f}}", top, left, bottom, right);
           if (frame_index < end_frame - 1) groups_result += ",\n    ";
         }
         groups_result += "}};\n";
       }
       groups_result += std::format("  static constexpr std::array<std::pair<std::string_view, "
                                    "compiled_texture::frame_data::group>, {}> {}_groups{{\n    {{",
                                    frame_groups.size(), name);
       auto sorted_frame_groups{frame_groups};
       std::sort(sorted_frame_groups.begin(), sorted_frame_groups.end(),
                 [](const auto &a, const auto &b) { return std::get<0>(a) < std::get<0>(b); });
       for (const auto &frame_group : sorted_frame_groups)
       {
         const auto &[group_name, frame_range]{frame_group};
         const auto &[start_frame, end_frame]{frame_range};
         groups_result +=
           std::format("{{\"{}\", {{{}, {}, {}_{}_frames}}}}", group_name, start_frame, end_frame, name, group_name);
         if (&frame_group != &sorted_frame_groups.back()) groups_result += ",\n     ";
       }
       groups_result += "}};";
       results.push_back(groups_result);

       return results;
     }},
    {[](const std::vector<std::tuple<std::filesystem::path, std::string, resource>> &files) -> std::string
     {
       std::string result{};
       for (const auto &[file, name, data] : files)
       {
         if (file.extension() == ".spv")
           result += std::format("  extern const compiled_shader {};\n", name);
         else
           result += std::format("  extern const compiled_texture {};\n", name);
       }
       return result + "}";
     },
     [](const std::vector<std::tuple<std::filesystem::path, std::string, resource>> &files) -> std::string
     {
       std::string result{};
       for (const auto &[file, name, data] : files)
       {
         if (file.extension() == ".spv")
           result += std::format("  const compiled_shader {}{{\n    {}_data,\n    {}}};\n", name, name,
                                 std::get<0>(data).size());
         else
         {
           const auto &[image_data, frame_data]{std::get<1>(data)};
           const auto &[width, height, channels]{image_data};
           const auto &[frame_dimensions, frame_groups]{frame_data};
           const auto &[frame_width, frame_height]{frame_dimensions};
           result += std::format("  const compiled_texture {}{{\n    {}_image,\n    "
                                 "{{{}, {}, {}}},\n    {{{}, {}, {}_groups}}}};\n",
                                 name, name, width, height, channels, frame_width, frame_height, name);
         }
       }
       return result + "}";
     }},
    [](const std::filesystem::path &file) -> bool { return file.extension() == ".spv" || file.extension() == ".png"; },
    csb::files_from({"build/shader", "program/texture"}),
    {"program/include/resource.hpp", "program/source/resource.cpp"});

  csb::vcpkg_install("2025.08.27", {{"builtin-baseline", "120deac3062162151622ca4860575a33844ba10b"},
                                    {"dependencies",
                                     {
                                       {
                                         {"name", "sdl3"},
                                         {"features", {"vulkan"}},
                                       },
                                       "glm",
                                     }},
                                    {"overrides",
                                     {
                                       {
                                         {"name", "sdl3"},
                                         {"version", "3.2.18"},
                                       },
                                       {
                                         {"name", "glm"},
                                         {"version", "1.0.1#3"},
                                       },
                                     }}});

  csb::generate_compile_commands();
  csb::compile();
  csb::link();
  return csb::run();
}

int csb::run()
{
  csb::run_target();
  return CSB_SUCCESS;
}

CSB_MAIN()
