include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/Manage.cmake")
set(SDL_VERSION "3.2.16")

CPMAddPackage(
  URI
  "gh:libsdl-org/SDL#release-${SDL_VERSION}"
  OPTIONS "SDL_INSTALL OFF" "SDL_UNINSTALL OFF" "SDL_INSTALL_TESTS OFF" "SDL_TESTS OFF"
)
list(
  APPEND
  SYSTEM_INCLUDE_DIRECTORIES
  "${CMAKE_CURRENT_BINARY_DIR}/_deps/sdl-src/include"
)
list(APPEND COMPILER_DEFINITIONS "SDL_MAIN_USE_CALLBACKS")
list(APPEND LIBRARIES "SDL3::SDL3")
